// dynamsoft/samples/frameworks/angular/scan-using-rtu-api/src/app/app.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { BarcodeScanner, BarcodeScannerConfig } from 'dynamsoft-barcode-reader-bundle';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class AppComponent {
  title = 'angular';
  barcodeScanner: BarcodeScanner | null = null;

  @ViewChild('barcodeScannerViewRef') barcodeScannerViewRef!: ElementRef<HTMLDivElement>;

  async ngAfterViewInit(): Promise<void> {
    // Configuration object for initializing the BarcodeScanner instance
    const config: BarcodeScannerConfig = {
      license: "DLS2eyJoYW5kc2hha2VDb2RlIjoiMTA0OTg1NDAzLU1UQTBPVGcxTkRBekxYZGxZaTFVY21saGJGQnliMm8iLCJtYWluU2VydmVyVVJMIjoiaHR0cHM6Ly9tZGxzLmR5bmFtc29mdG9ubGluZS5jb20vIiwib3JnYW5pemF0aW9uSUQiOiIxMDQ5ODU0MDMiLCJzdGFuZGJ5U2VydmVyVVJMIjoiaHR0cHM6Ly9zZGxzLmR5bmFtc29mdG9ubGluZS5jb20vIiwiY2hlY2tDb2RlIjotMjEyMzYxNzIwfQ==", // Replace with your Dynamsoft license key

      // Specify where to render the scanner UI
      // If container is not specified, the UI will take up the full screen
      container: this.barcodeScannerViewRef.nativeElement, 

      // Specify the path for the definition file "barcode-scanner.ui.xml" for the scanner view.
      uiPath: "https://cdn.jsdelivr.net/npm/dynamsoft-barcode-reader-bundle@11.2.4000/dist/ui/barcode-scanner.ui.xml",

      // showUploadImageButton: true,
      // scannerViewConfig: {
      //   showFlashButton: true,
      //   cameraSwitchControl: "toggleFrontBack",
      // },

      // Specify custom paths for the engine resources
      engineResourcePaths: {
        rootDirectory: "https://cdn.jsdelivr.net/npm/",
      },
    }

    // Create an instance of the BarcodeScanner with the provided configuration
    this.barcodeScanner = new BarcodeScanner(config);

    // Launch the scanner; once a barcode is detected, display its text in an alert
    let result = await this.barcodeScanner.launch();
    if (result.barcodeResults.length) {
      alert(result.barcodeResults[0].text);
    }
  }
  async ngOnDestroy(): Promise<void> { 
    // Dispose of the barcode scanner when the component unmounts
    this.barcodeScanner?.dispose();
  }
}

// dynamsoft/samples/frameworks/react/scan-using-rtu-api/src/App.tsx
import { useEffect, useRef  } from 'react';
import { BarcodeScanner, type BarcodeScannerConfig } from "dynamsoft-barcode-reader-bundle";


function App() {
  const barcodeScannerViewRef = useRef(null);
  
  useEffect(() => {

    // Configuration object for initializing the BarcodeScanner instance
    const config: BarcodeScannerConfig = {
      license: "DLS2eyJoYW5kc2hha2VDb2RlIjoiMTA0OTg1NDAzLU1UQTBPVGcxTkRBekxYZGxZaTFVY21saGJGQnliMm8iLCJtYWluU2VydmVyVVJMIjoiaHR0cHM6Ly9tZGxzLmR5bmFtc29mdG9ubGluZS5jb20vIiwib3JnYW5pemF0aW9uSUQiOiIxMDQ5ODU0MDMiLCJzdGFuZGJ5U2VydmVyVVJMIjoiaHR0cHM6Ly9zZGxzLmR5bmFtc29mdG9ubGluZS5jb20vIiwiY2hlY2tDb2RlIjotMjEyMzYxNzIwfQ==", // Replace with your Dynamsoft license key

      // Specify where to render the scanner UI
      // If container is not specified, the UI will take up the full screen
      container: barcodeScannerViewRef.current!, 

      // Specify the path for the definition file "barcode-scanner.ui.xml" for the scanner view.
      uiPath: "https://cdn.jsdelivr.net/npm/dynamsoft-barcode-reader-bundle@11.2.4000/dist/ui/barcode-scanner.ui.xml",

      // showUploadImageButton: true,
      // scannerViewConfig: {
      //   showFlashButton: true,
      //   cameraSwitchControl: "toggleFrontBack",
      // },

      // Specify custom paths for the engine resources
      engineResourcePaths: {
        rootDirectory: "https://cdn.jsdelivr.net/npm/",
      },
    }

    // Create an instance of the BarcodeScanner with the provided configuration
    const barcodeScanner = new BarcodeScanner(config);

    (async ()=>{
      // Launch the scanner; once a barcode is detected, display its text in an alert
      let result = await barcodeScanner.launch();
      if (result.barcodeResults.length) {
        alert(result.barcodeResults[0].text);
      }
    })();

    return ()=>{
      // Dispose of the barcode scanner when the component unmounts
      barcodeScanner?.dispose();
    };
  }, []);

  return (
    <>
      <h1>Barcode Scanner for React</h1>
      <div ref={barcodeScannerViewRef} style={{ width: '100%', height: '80vh' }}>
      </div>
    </>
  )
}

export default App
